### ISSUE TITLE
Задание 2 

### ISSUE THREAD

**Issue by djadjka** [Inunor/AntBakatovich#2]
а вот не все из тз есть

**Comment by Inunor** [comment]
Добрый день, можно узнать в чем причина снижения баллов и возможно исправить недочёт?

**Comment by djadjka** [comment]
Читай коменты в пр-е

**Comment by djadjka** [comment]
Да, можно доделать

**Comment by Inunor** [comment]
Добавил подсказки для хэштегов

**Comment by djadjka** [comment]
и на стр добавления тоже надо
и пофикси фильтр, будет 10

**Comment by Inunor** [comment]
Добавил фильтр
